---
title: "Subject1 Comparasion Graphs"
author: "Kebin Yan"
date: "3/11/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
source("~/Desktop/WFU/URECA/R_template/Compare Prediction Graphs.R")
source("~/Desktop/WFU/URECA/R_template/Examining Time Difference.R")
```

```{r}
combined_result_step1 <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step1/front_pred.csv")
acc_result_step1 <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step1/acc_front_pred.csv")
gyro_result_step1 <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step1/gyro_front_pred.csv")
```

```{r}
activityList <- c("walk", "stand","stairUp", "stairDown","standToSit","sit","sitToStand")
activityCols <-  c("#000000", "#56B4E9", "#E69F00", "#009E73", "#F0E442", "#CC79A7", "#D55E00")
```

# Comparison Graph for Step 1
```{r}
time_difference_step1 <- CalculateTimeDifference(acc_result_step1, gyro_result_step1)
gyro_on_acc_time_step1 <- GyroOnAccTime(acc_result_step1, gyro_result_step1,time_difference_step1)
pdf(file = "~/Desktop/Prediction Graphs/subject1/step1.pdf")
combinedPlotActivityPrediction(acc_result_step1, gyro_on_acc_time_step1, combined_result_step1, NA, activityList, activityCols, TRUE)
dev.off()
```

\newpage
# Comparison Graph for Step 2
```{r}
combined_result_step2 <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step2/front_pred.csv")
acc_result_step2 <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step2/acc_front_pred.csv")
gyro_result_step2 <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step2/gyro_front_pred.csv")
```

```{r}
time_difference_step2 <- CalculateTimeDifference(acc_result_step2, gyro_result_step2)
gyro_on_acc_time_step2 <- GyroOnAccTime(acc_result_step2, gyro_result_step2,time_difference_step2)
pdf(file = "~/Desktop/Prediction Graphs/subject1/step2.pdf")
combinedPlotActivityPrediction(acc_result_step2, gyro_on_acc_time_step2, combined_result_step2, NA, activityList, activityCols, TRUE)
dev.off()
```

\newpage
# Comparison Graph for Step 3 Fast Walk
```{r}
combined_result_step3_fastWalk <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step3/front_pred_fast.csv")
acc_result_step3_fastWalk <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step3/acc_front_pred_fast.csv")
gyro_result_step3_fastWalk <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step3/gyro_front_pred_fast.csv")
```

```{r}
time_difference_step3_fastWalk <- CalculateTimeDifference(acc_result_step3_fastWalk, gyro_result_step3_fastWalk)
gyro_on_acc_time_step3_fastWalk <- GyroOnAccTime(acc_result_step3_fastWalk, gyro_result_step3_fastWalk,time_difference_step3_fastWalk)
pdf(file = "~/Desktop/Prediction Graphs/subject1/step3_fast_walk.pdf")
combinedPlotActivityPrediction(acc_result_step3_fastWalk, gyro_on_acc_time_step3_fastWalk, combined_result_step3_fastWalk, NA, activityList, activityCols, TRUE)
dev.off()
```

\newpage
# Comparison Graph for Step 3 Normal Walk
```{r}
combined_result_step3_normalWalk <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step3/front_pred_normal.csv")
acc_result_step3_normalWalk <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step3/acc_front_pred_normal.csv")
gyro_result_step3_normalWalk <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step3/gyro_front_pred_normal.csv")
```

```{r}
time_difference_step3_normalWalk <- CalculateTimeDifference(acc_result_step3_normalWalk, gyro_result_step3_normalWalk)
gyro_on_acc_time_step3_normalWalk <- GyroOnAccTime(acc_result_step3_normalWalk, acc_result_step3_normalWalk,time_difference_step3_normalWalk)
pdf(file = "~/Desktop/Prediction Graphs/subject1/step3_normal_walk.pdf")
combinedPlotActivityPrediction(acc_result_step3_normalWalk, gyro_on_acc_time_step3_normalWalk, combined_result_step3_normalWalk, NA, activityList, activityCols, TRUE)
dev.off()
```

\newpage
# Comparison Graph for Step 3 Slow Walk
```{r}
combined_result_step3_slowWalk <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step3/front_pred_slow.csv")
acc_result_step3_slowWalk <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step3/acc_front_pred_slow.csv")
gyro_result_step3_slowWalk <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step3/gyro_front_pred_slow.csv")
```

```{r}
time_difference_step3_slowWalk <- CalculateTimeDifference(acc_result_step3_slowWalk, gyro_result_step3_slowWalk)
gyro_on_acc_time_step3_slowWalk <- GyroOnAccTime(acc_result_step3_slowWalk, gyro_result_step3_slowWalk,time_difference_step3_slowWalk)
pdf(file = "~/Desktop/Prediction Graphs/subject1/step3_slow_walk.pdf")
combinedPlotActivityPrediction(acc_result_step3_slowWalk, gyro_on_acc_time_step3_slowWalk, combined_result_step3_slowWalk, NA, activityList, activityCols, TRUE)
dev.off()
```

\newpage
# Comparison Graph for Step 5
```{r}
combined_result_step5 <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step5/front_pred.csv")
acc_result_step5 <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step5/acc_front_pred.csv")
gyro_result_step5 <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step5/gyro_front_pred.csv")
```

```{r}
time_difference_step5 <- CalculateTimeDifference(acc_result_step5, gyro_result_step5)
gyro_on_acc_time_step5 <- GyroOnAccTime(acc_result_step5, gyro_result_step5, time_difference_step5)
pdf(file = "~/Desktop/Prediction Graphs/subject1/step5.pdf")
combinedPlotActivityPrediction(acc_result_step5, gyro_on_acc_time_step5, combined_result_step5, NA, activityList, activityCols, TRUE)
dev.off()
```

\newpage
# Comparison Graph for Step 6 Stair Up
```{r}
combined_result_step6_stairDown <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step6/stairDown/front_pred.csv")
acc_result_step6_stairDown <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step6/stairDown/acc_front_pred.csv")
gyro_result_step6_stairDown <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step6/stairDown/gyro_front_pred.csv")
```

```{r}
time_difference_step6_stairDown <- CalculateTimeDifference(acc_result_step6_stairDown, gyro_result_step6_stairDown)
gyro_on_acc_time_step6_stairDown <- GyroOnAccTime(acc_result_step6_stairDown, gyro_result_step6_stairDown, time_difference_step6_stairDown)
pdf(file = "~/Desktop/Prediction Graphs/subject1/step6_stair_down.pdf")
combinedPlotActivityPrediction(acc_result_step6_stairDown, gyro_on_acc_time_step6_stairDown, combined_result_step6_stairDown, NA, activityList, activityCols, TRUE)
dev.off()
```

\newpage
# Comparison Graph for Step 6 Stair Down
```{r}
combined_result_step6_stairUp <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step6/stairUp/front_pred.csv")
acc_result_step6_stairUp <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step6/stairUp/acc_front_pred.csv")
gyro_result_step6_stairUp <- read.csv("~/Desktop/csv/subject1/test/Prediction/Step6/stairUp/gyro_front_pred.csv")
```

```{r}
time_difference_step6_stairUp <- CalculateTimeDifference(acc_result_step6_stairUp, gyro_result_step6_stairUp)
gyro_on_acc_time_step6_stairUp <- GyroOnAccTime(acc_result_step6_stairUp, gyro_result_step6_stairUp, time_difference_step6_stairUp)
pdf(file = "~/Desktop/Prediction Graphs/subject1/step6_stair_up.pdf")
combinedPlotActivityPrediction(acc_result_step6_stairUp, gyro_on_acc_time_step6_stairUp, combined_result_step6_stairUp, NA, activityList, activityCols, TRUE)
dev.off()
```

