---
title: "Subject 4 Confusion Matrices"
author: "Kebin Yan"
date: "5/28/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, include=FALSE}
source("~/Desktop/WFU/URECA/R_template/Plot Confusion Matrix.R")
```


```{r}
combined_result_step1 <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step1/revised_combined_front_pred.csv")
acc_result_step1 <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step1/revised_acc_front_pred.csv")
gyro_result_step1 <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step1/revised_gyro_on_acc_front_pred.csv")

combined_result_step2 <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step2/revised_combined_front_pred.csv")
acc_result_step2 <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step2/revised_acc_front_pred.csv")
gyro_result_step2 <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step2/revised_gyro_on_acc_front_pred.csv")

combined_result_step3_fastWalk <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step3/fast_walk/revised_combined_front_pred_fast.csv")
acc_result_step3_fastWalk <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step3/fast_walk/revised_acc_front_pred_fast.csv")
gyro_result_step3_fastWalk <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step3/fast_walk/revised_gyro_on_acc_front_pred_fast.csv")

combined_result_step3_normalWalk <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step3/normal_walk/revised_combined_front_pred_normal.csv")
acc_result_step3_normalWalk <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step3/normal_walk/revised_acc_front_pred_normal.csv")
gyro_result_step3_normalWalk <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step3/normal_walk/revised_gyro_on_acc_front_pred_normal.csv")

combined_result_step3_slowWalk <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step3/slow_walk/revised_combined_front_pred_slow.csv")
acc_result_step3_slowWalk <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step3/slow_walk/revised_acc_front_pred_slow.csv")
gyro_result_step3_slowWalk <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step3/slow_walk/revised_gyro_on_acc_front_pred_slow.csv")

combined_result_step5 <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step5/revised_combined_front_pred.csv")
acc_result_step5 <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step5/revised_acc_front_pred.csv")
gyro_result_step5 <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step5/revised_gyro_on_acc_front_pred.csv")

combined_result_step6_stairDown <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step6/stairDown/revised_combined_front_pred.csv")
acc_result_step6_stairDown <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step6/stairDown/revised_acc_front_pred.csv")
gyro_result_step6_stairDown <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step6/stairDown/revised_gyro_on_acc_front_pred.csv")

combined_result_step6_stairUp <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step6/stairUp/revised_combined_front_pred.csv")
acc_result_step6_stairUp <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step6/stairUp/revised_acc_front_pred.csv")
gyro_result_step6_stairUp <- read.csv("~/Desktop/csv/subject4/test/Prediction/Step6/stairUp/revised_gyro_on_acc_front_pred.csv")
```

```{r}
Activities <- c("walk", "standToSit", "stand", "stairUp", "stairDown", "sitToStand", "sit", "revolving door")
```

## Step 1

```{r}
acc_result_step1$label <- as.factor(acc_result_step1$label)
acc_result_step1$label.predict <- as.factor(acc_result_step1$label.predict)
acc_result_step1$movelet.label <- as.factor(acc_result_step1$movelet.label)

gyro_result_step1$label <- as.factor(gyro_result_step1$label)
gyro_result_step1$label.predict <- as.factor(gyro_result_step1$label.predict)
gyro_result_step1$movelet.label <- as.factor(gyro_result_step1$movelet.label)

combined_result_step1$label <- as.factor(combined_result_step1$label)
combined_result_step1$label.predict <- as.factor(combined_result_step1$label.predict)
combined_result_step1$movelet.label <- as.factor(combined_result_step1$movelet.label)
```

```{r, warning=FALSE, fig.asp=1.1}
pdf(file = "~/Desktop/Confusion Matrix/subject4/step1_acc.pdf")
plotConfusionMatrix(acc_result_step1, Activities, TRUE)
dev.off()

pdf(file = "~/Desktop/Confusion Matrix/subject4/step1_gyro.pdf")
plotConfusionMatrix(gyro_result_step1, Activities, TRUE)
dev.off()

pdf(file = "~/Desktop/Confusion Matrix/subject4/step1_combined.pdf")
plotConfusionMatrix(combined_result_step1, Activities, TRUE)
dev.off()
```


## Step 2

```{r}
acc_result_step2$label <- as.factor(acc_result_step2$label)
acc_result_step2$label.predict <- as.factor(acc_result_step2$label.predict)
acc_result_step2$movelet.label <- as.factor(acc_result_step2$movelet.label)

gyro_result_step2$label <- as.factor(gyro_result_step2$label)
gyro_result_step2$label.predict <- as.factor(gyro_result_step2$label.predict)
gyro_result_step2$movelet.label <- as.factor(gyro_result_step2$movelet.label)

combined_result_step2$label <- as.factor(combined_result_step2$label)
combined_result_step2$label.predict <- as.factor(combined_result_step2$label.predict)
combined_result_step2$movelet.label <- as.factor(combined_result_step2$movelet.label)
```

```{r, warning=FALSE, fig.asp=1.1}
# par(mfrow = c(3,1))
pdf(file = "~/Desktop/Confusion Matrix/subject4/step2_acc.pdf")
plotConfusionMatrix(acc_result_step2, Activities, TRUE)
dev.off()

pdf(file = "~/Desktop/Confusion Matrix/subject4/step2_gyro.pdf")
plotConfusionMatrix(gyro_result_step2, Activities, TRUE)
dev.off()

pdf(file = "~/Desktop/Confusion Matrix/subject4/step2_combined.pdf")
plotConfusionMatrix(combined_result_step2, Activities, TRUE)
dev.off()
```


## Step 3

```{r}
acc_result_step3 <- rbind(acc_result_step3_fastWalk, acc_result_step3_normalWalk, acc_result_step3_slowWalk)
gyro_result_step3 <- rbind(gyro_result_step3_fastWalk, gyro_result_step3_normalWalk, gyro_result_step3_slowWalk)
combined_result_step3 <- rbind(combined_result_step3_fastWalk, combined_result_step3_normalWalk, combined_result_step3_slowWalk)
```

```{r}
acc_result_step3$label <- as.factor(acc_result_step3$label)
acc_result_step3$label.predict <- as.factor(acc_result_step3$label.predict)
acc_result_step3$movelet.label <- as.factor(acc_result_step3$movelet.label)

gyro_result_step3$label <- as.factor(gyro_result_step3$label)
gyro_result_step3$label.predict <- as.factor(gyro_result_step3$label.predict)
gyro_result_step3$movelet.label <- as.factor(gyro_result_step3$movelet.label)

combined_result_step3$label <- as.factor(combined_result_step3$label)
combined_result_step3$label.predict <- as.factor(combined_result_step3$label.predict)
combined_result_step3$movelet.label <- as.factor(combined_result_step3$movelet.label)
```

```{r, warning=FALSE, fig.asp=1.1}
# par(mfrow = c(3,1))
pdf(file = "~/Desktop/Confusion Matrix/subject4/step3_acc.pdf")
plotConfusionMatrix(acc_result_step3, Activities, TRUE)
dev.off()

pdf(file = "~/Desktop/Confusion Matrix/subject4/step3_gyro.pdf")
plotConfusionMatrix(gyro_result_step3, Activities, TRUE)
dev.off()

pdf(file = "~/Desktop/Confusion Matrix/subject4/step3_combined.pdf")
plotConfusionMatrix(combined_result_step3, Activities, TRUE)
dev.off()
```

## Step 5

```{r}
acc_result_step5$label <- as.factor(acc_result_step5$label)
acc_result_step5$label.predict <- as.factor(acc_result_step5$label.predict)
acc_result_step5$movelet.label <- as.factor(acc_result_step5$movelet.label)

gyro_result_step5$label <- as.factor(gyro_result_step5$label)
gyro_result_step5$label.predict <- as.factor(gyro_result_step5$label.predict)
gyro_result_step5$movelet.label <- as.factor(gyro_result_step5$movelet.label)

combined_result_step5$label <- as.factor(combined_result_step5$label)
combined_result_step5$label.predict <- as.factor(combined_result_step5$label.predict)
combined_result_step5$movelet.label <- as.factor(combined_result_step5$movelet.label)
```

```{r, warning=FALSE, fig.asp=1.1}
# par(mfrow = c(3,1))
pdf(file = "~/Desktop/Confusion Matrix/subject4/step5_acc.pdf")
plotConfusionMatrix(acc_result_step5, Activities, TRUE)
dev.off()

pdf(file = "~/Desktop/Confusion Matrix/subject4/step5_gyro.pdf")
plotConfusionMatrix(gyro_result_step5, Activities, TRUE)
dev.off()

pdf(file = "~/Desktop/Confusion Matrix/subject4/step5_combined.pdf")
plotConfusionMatrix(combined_result_step5, Activities, TRUE)
dev.off()
```

## Step 6

```{r}
acc_result_step6 <- rbind(acc_result_step6_stairUp, acc_result_step6_stairDown)
gyro_result_step6 <- rbind(gyro_result_step6_stairUp, gyro_result_step6_stairDown)
combined_result_step6 <- rbind(combined_result_step6_stairUp, combined_result_step6_stairDown)
```

```{r}
acc_result_step6$label <- as.factor(acc_result_step6$label)
acc_result_step6$label.predict <- as.factor(acc_result_step6$label.predict)
acc_result_step6$movelet.label <- as.factor(acc_result_step6$movelet.label)

gyro_result_step6$label <- as.factor(gyro_result_step6$label)
gyro_result_step6$label.predict <- as.factor(gyro_result_step6$label.predict)
gyro_result_step6$movelet.label <- as.factor(gyro_result_step6$movelet.label)

combined_result_step6$label <- as.factor(combined_result_step6$label)
combined_result_step6$label.predict <- as.factor(combined_result_step6$label.predict)
combined_result_step6$movelet.label <- as.factor(combined_result_step6$movelet.label)
```

```{r, warning=FALSE, fig.asp=1.1}
# par(mfrow = c(3,1))
pdf(file = "~/Desktop/Confusion Matrix/subject4/step6_acc.pdf")
plotConfusionMatrix(acc_result_step6, Activities, TRUE)
dev.off()

pdf(file = "~/Desktop/Confusion Matrix/subject4/step6_gyro.pdf")
plotConfusionMatrix(gyro_result_step6, Activities, TRUE)
dev.off()

pdf(file = "~/Desktop/Confusion Matrix/subject4/step6_combined.pdf")
plotConfusionMatrix(combined_result_step6, Activities, TRUE)
dev.off()
```

```{r}
acc_result_summary <- rbind(acc_result_step1, acc_result_step2, acc_result_step3, acc_result_step5, acc_result_step6)
gyro_result_summary <- rbind(gyro_result_step1, gyro_result_step2, gyro_result_step3, gyro_result_step5, gyro_result_step6)
combined_result_summary <- rbind(combined_result_step1, combined_result_step2, combined_result_step3, combined_result_step5, combined_result_step6)
```

```{r, warning=FALSE, fig.asp=1.1}
pdf(file = "~/Desktop/Confusion Matrix/subject4/all_steps_acc.pdf")
plotConfusionMatrix(acc_result_summary, Activities, TRUE)
dev.off()

pdf(file = "~/Desktop/Confusion Matrix/subject4/all_steps_gyro.pdf")
plotConfusionMatrix(gyro_result_summary, Activities, TRUE)
dev.off()

pdf(file = "~/Desktop/Confusion Matrix/subject4/all_steps_combined.pdf")
plotConfusionMatrix(combined_result_summary, Activities, TRUE)
dev.off()
```